### ISSUE TITLE
feat(explanations): add tool tips to menu items

### ISSUE THREAD

**Issue by ShragaUser** [ShragaUser/BlueBoard#11]
**All menu items on board should have a tool tip or explanation Modal.**

#### example: 
- leave board ( on hover ): "pushing this button removes you from this board but does not delete the board for other users"
- delete board ( on hover ): "pushing this button will delete the board for you and **all** other members of the board!" 

##### for your consideration:
maybe save a "don`t show me again" on the Modal helper. 
or just use a tool tip if that works.

**Comment by baradm100** [comment]
@ShragaUser Please leave the `good first issue` for other (Like @ZEShahar )
